{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: dlsidecar
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $value := .Values.secrets }}
    - secretKey: DLS_{{ $key | upper }}
      remoteRef:
        key: dlsidecar/{{ $.Release.Namespace }}/dls_{{ $key }}
        property: value
    {{- end }}
{{- end }}
